.CODE ; DEFUN/IDENT
.FALIGN ; DEFUN/IDENT
fact ; DEFUN/IDENT
ADD R6, R6, #-3 ; DEFUN/IDENT
STR R7, R6, #1 ; DEFUN/IDENT
STR R5, R6, #0 ; DEFUN/IDENT
ADD R5, R6, #0 ; DEFUN/IDENT
LDR R0, R6, #0 ; DUP
ADD R6, R6, #-1 ; DUP
STR R0, R6, #0 ; DUP
ADD R6 R6 #-1 ; LITERAL
CONST R0 #1 ; LITERAL
HICONST R0 #0 ; LITERAL
STR R0 R6 #0 ; LITERAL
LDR R0, R6, #0 ; GE
LDR R1, R6, #1 ; GE
CMP R0, R1; GE
BRzp TRUE_L_0 ; GE
BRn FALSE_L_0 ; GE
TRUE_L_0 ; GE
CONST R2, #1 ; GE
BRnzp TERMINATE_L_0 ; GE
FALSE_L_0 ; GE
CONST R2, #0 ; GE
BRnzp TERMINATE_L_0 ; GE
TERMINATE_L_0 ; GE
ADD R6, R6, #1; GE
STR R2, R6, #0 ; GE
ADD R6, R6, #1 ; IF
LDR R0, R6, #-1 ; IF
BRnz ELSE_BRANCH_0 ; IF
ADD R6 R6 #-1 ; LITERAL
CONST R0 #1 ; LITERAL
HICONST R0 #0 ; LITERAL
STR R0 R6 #0 ; LITERAL
JMP ENDIF_BRANCH_0 ; ELSE
ELSE_BRANCH_0 ; ELSE
LDR R0, R6, #0 ; DUP
ADD R6, R6, #-1 ; DUP
STR R0, R6, #0 ; DUP
ADD R6 R6 #-1 ; LITERAL
CONST R0 #1 ; LITERAL
HICONST R0 #0 ; LITERAL
STR R0 R6 #0 ; LITERAL
LDR R0, R6, #0 ; SWAP
LDR R1, R6, #1 ; SWAP
STR R0, R6, #1 ; SWAP
STR R1, R6, #0 ; SWAP
LDR R0, R6, #0 ; MINUS
LDR R1, R6, #1 ; MINUS
SUB R0, R0, R1 ; MINUS
ADD R6, R6, #1 ; MINUS
STR R0, R6, #0 ; MINUS
JSR fact ; IDENT
ADD R6, R6, #-1 ; IDENT
LDR R0, R6, #0 ; SWAP
LDR R1, R6, #1 ; SWAP
STR R0, R6, #1 ; SWAP
STR R1, R6, #0 ; SWAP
ADD R6, R6, #1 ; DROP
LDR R0, R6, #0 ; MUL
LDR R1, R6, #1 ; MUL
MUL R0, R0, R1 ; MUL
ADD R6, R6, #1 ; MUL
STR R0, R6, #0 ; MUL
ENDIF_BRANCH_0 ; ENDIF
LDR R7, R6, #0 ; RETURN
STR R7, R5, #2 ; RETURN
ADD R6, R5, #0 ; RETURN
LDR R5, R6, #0 ; RETURN
LDR R7, R6, #1 ; RETURN
ADD R6, R6, #3 ; RETURN
RET ; RETURN
.CODE ; DEFUN/IDENT
.FALIGN ; DEFUN/IDENT
main ; DEFUN/IDENT
ADD R6, R6, #-3 ; DEFUN/IDENT
STR R7, R6, #1 ; DEFUN/IDENT
STR R5, R6, #0 ; DEFUN/IDENT
ADD R5, R6, #0 ; DEFUN/IDENT
ADD R6 R6 #-1 ; LITERAL
CONST R0 #4 ; LITERAL
HICONST R0 #0 ; LITERAL
STR R0 R6 #0 ; LITERAL
JSR fact ; IDENT
ADD R6, R6, #-1 ; IDENT
JSR printnum ; IDENT
ADD R6, R6, #-1 ; IDENT
JSR endl ; IDENT
ADD R6, R6, #-1 ; IDENT
ADD R6 R6 #-1 ; LITERAL
CONST R0 #5 ; LITERAL
HICONST R0 #0 ; LITERAL
STR R0 R6 #0 ; LITERAL
JSR fact ; IDENT
ADD R6, R6, #-1 ; IDENT
JSR printnum ; IDENT
ADD R6, R6, #-1 ; IDENT
JSR endl ; IDENT
ADD R6, R6, #-1 ; IDENT
ADD R6 R6 #-1 ; LITERAL
CONST R0 #6 ; LITERAL
HICONST R0 #0 ; LITERAL
STR R0 R6 #0 ; LITERAL
JSR fact ; IDENT
ADD R6, R6, #-1 ; IDENT
JSR printnum ; IDENT
ADD R6, R6, #-1 ; IDENT
JSR endl ; IDENT
ADD R6, R6, #-1 ; IDENT
ADD R6 R6 #-1 ; LITERAL
CONST R0 #7 ; LITERAL
HICONST R0 #0 ; LITERAL
STR R0 R6 #0 ; LITERAL
JSR fact ; IDENT
ADD R6, R6, #-1 ; IDENT
JSR printnum ; IDENT
ADD R6, R6, #-1 ; IDENT
JSR endl ; IDENT
ADD R6, R6, #-1 ; IDENT
LDR R7, R6, #0 ; RETURN
STR R7, R5, #2 ; RETURN
ADD R6, R5, #0 ; RETURN
LDR R5, R6, #0 ; RETURN
LDR R7, R6, #1 ; RETURN
ADD R6, R6, #3 ; RETURN
RET ; RETURN
