.CODE ; DEFUN/IDENT
.FALIGN ; DEFUN/IDENT
main ; DEFUN/IDENT
ADD R6, R6, #-3 ; DEFUN/IDENT
STR R7, R6, #1 ; DEFUN/IDENT
STR R5, R6, #0 ; DEFUN/IDENT
ADD R5, R6, #0 ; DEFUN/IDENT
ADD R6 R6 #-1 ; LITERAL
CONST R0 #5 ; LITERAL
HICONST R0 #0 ; LITERAL
STR R0 R6 #0 ; LITERAL
ADD R6 R6 #-1 ; LITERAL
CONST R0 #3 ; LITERAL
HICONST R0 #0 ; LITERAL
STR R0 R6 #0 ; LITERAL
LDR R0, R6, #0 ; GT
LDR R1, R6, #1 ; GT
CMP R0, R1; GT
BRp TRUE_L_0 ; GT
BRnz FALSE_L_0 ; GT
TRUE_L_0 ; GT
CONST R2, #1 ; GT
BRnzp TERMINATE_L_0 ; GT
FALSE_L_0 ; GT
CONST R2, #0 ; GT
BRnzp TERMINATE_L_0 ; GT
TERMINATE_L_0 ; GT
ADD R6, R6, #1; GT
STR R2, R6, #0 ; GT
JSR printnum ; IDENT
ADD R6, R6, #-1 ; IDENT
JSR endl ; IDENT
ADD R6, R6, #-1 ; IDENT
ADD R6 R6 #-1 ; LITERAL
CONST R0 #88 ; LITERAL
HICONST R0 #27 ; LITERAL
STR R0 R6 #0 ; LITERAL
ADD R6 R6 #-1 ; LITERAL
CONST R0 #190 ; LITERAL
HICONST R0 #252 ; LITERAL
STR R0 R6 #0 ; LITERAL
LDR R0, R6, #0 ; LT
LDR R1, R6, #1 ; LT
CMP R0, R1; LT
BRn TRUE_L_1 ; LT
BRzp FALSE_L_1 ; LT
TRUE_L_1 ; LT
CONST R2, #1 ; LT
BRnzp TERMINATE_L_1 ; LT
FALSE_L_1 ; LT
CONST R2, #0 ; LT
BRnzp TERMINATE_L_1 ; LT
TERMINATE_L_1 ; LT
ADD R6, R6, #1; LT
STR R2, R6, #0 ; LT
JSR printnum ; IDENT
ADD R6, R6, #-1 ; IDENT
JSR endl ; IDENT
ADD R6, R6, #-1 ; IDENT
LDR R7, R6, #0 ; RETURN
STR R7, R5, #2 ; RETURN
ADD R6, R5, #0 ; RETURN
LDR R5, R6, #0 ; RETURN
LDR R7, R6, #1 ; RETURN
ADD R6, R6, #3 ; RETURN
RET ; RETURN
